/**
 * This file was generated by:
 *   relay-compiler
 *
 * @providesModule UserMenu_user.graphql
 * @generated SignedSource<<ef61102e40766e31930a4eeb3eb36614>>
 * @flow
 * @nogrep
 */

/* eslint-disable */

'use strict';

/*::
import type {ConcreteFragment} from 'relay-runtime';
export type UserMenu_user = {|
  +username: ?string;
|};
*/


const fragment /*: ConcreteFragment*/ = {
  "argumentDefinitions": [],
  "kind": "Fragment",
  "metadata": null,
  "name": "UserMenu_user",
  "selections": [
    {
      "kind": "ScalarField",
      "alias": null,
      "args": null,
      "name": "username",
      "storageKey": null
    }
  ],
  "type": "User"
};

module.exports = fragment;
