/**
 * This file was generated by:
 *   relay-compiler
 *
 * @providesModule NotePane_node.graphql
 * @generated SignedSource<<4c448f51b7abbdc6d10f876789d175e2>>
 * @flow
 * @nogrep
 */

/* eslint-disable */

'use strict';

/*::
import type {ConcreteFragment} from 'relay-runtime';
export type NotePane_node = {|
  +id: string;
  +content: ?string;
|};
*/


const fragment /*: ConcreteFragment*/ = {
  "argumentDefinitions": [
    {
      "kind": "RootArgument",
      "name": "previewOnly",
      "type": "Boolean"
    }
  ],
  "kind": "Fragment",
  "metadata": null,
  "name": "NotePane_node",
  "selections": [
    {
      "kind": "ScalarField",
      "alias": null,
      "args": null,
      "name": "id",
      "storageKey": null
    },
    {
      "kind": "ScalarField",
      "alias": null,
      "args": [
        {
          "kind": "Variable",
          "name": "preview",
          "variableName": "previewOnly",
          "type": "Boolean"
        }
      ],
      "name": "content",
      "storageKey": null
    }
  ],
  "type": "NoteNode"
};

module.exports = fragment;
