/**
 * This file was generated by:
 *   relay-compiler
 *
 * @providesModule AppRoot_user.graphql
 * @generated SignedSource<<da698ebc2e5501f4b9d477a93a55352e>>
 * @flow
 * @nogrep
 */

/* eslint-disable */

'use strict';

/*::
import type {ConcreteFragment} from 'relay-runtime';
export type AppRoot_user = {|
  +lastSelectedRoot: ?{|
    +lastEditedNode: ?{|
      +id: string;
      +leftBound: ?number;
      +rightBound: ?number;
      +content: ?string;
    |};
    +nodes: ?$ReadOnlyArray<?{|
      +id: string;
      +leftBound: ?number;
      +rightBound: ?number;
    |}>;
  |};
|};
*/


const fragment /*: ConcreteFragment*/ = {
  "argumentDefinitions": [],
  "kind": "Fragment",
  "metadata": null,
  "name": "AppRoot_user",
  "selections": [
    {
      "kind": "FragmentSpread",
      "name": "NavBar_user",
      "args": null
    },
    {
      "kind": "LinkedField",
      "alias": null,
      "args": null,
      "concreteType": "Root",
      "name": "lastSelectedRoot",
      "plural": false,
      "selections": [
        {
          "kind": "FragmentSpread",
          "name": "AddDeleteNoteMutation_lastSelectedRoot",
          "args": null
        },
        {
          "kind": "FragmentSpread",
          "name": "MoveNodeMutation_lastSelectedRoot",
          "args": null
        },
        {
          "kind": "LinkedField",
          "alias": null,
          "args": null,
          "concreteType": "NoteNode",
          "name": "lastEditedNode",
          "plural": false,
          "selections": [
            {
              "kind": "ScalarField",
              "alias": null,
              "args": null,
              "name": "id",
              "storageKey": null
            },
            {
              "kind": "ScalarField",
              "alias": null,
              "args": null,
              "name": "leftBound",
              "storageKey": null
            },
            {
              "kind": "ScalarField",
              "alias": null,
              "args": null,
              "name": "rightBound",
              "storageKey": null
            },
            {
              "kind": "ScalarField",
              "alias": null,
              "args": [
                {
                  "kind": "Literal",
                  "name": "preview",
                  "value": false,
                  "type": "Boolean"
                }
              ],
              "name": "content",
              "storageKey": "content{\"preview\":false}"
            }
          ],
          "storageKey": null
        },
        {
          "kind": "LinkedField",
          "alias": null,
          "args": null,
          "concreteType": "NoteNode",
          "name": "nodes",
          "plural": true,
          "selections": [
            {
              "kind": "ScalarField",
              "alias": null,
              "args": null,
              "name": "id",
              "storageKey": null
            },
            {
              "kind": "ScalarField",
              "alias": null,
              "args": null,
              "name": "leftBound",
              "storageKey": null
            },
            {
              "kind": "ScalarField",
              "alias": null,
              "args": null,
              "name": "rightBound",
              "storageKey": null
            },
            {
              "kind": "FragmentSpread",
              "name": "NotePane_node",
              "args": null
            }
          ],
          "storageKey": null
        }
      ],
      "storageKey": null
    }
  ],
  "type": "User"
};

module.exports = fragment;
